// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for Pigeon communication
struct PigeonError: Error {
  let code: String
  let message: String?
  let details: String?
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 后台任务配置设置
///
/// Generated class from Pigeon that represents data sent in messages.
struct BackgroundWorkerSettings {
  /// 是否要求充电
  var requiresCharging: Bool
  /// 是否要求电池不低
  var requiresBatteryNotLow: Bool
  /// 最小延迟秒数
  var minimumDelaySeconds: Int64
  /// 网络类型要求（true表示需要WiFi，false表示不限制）
  var requiresNetworkType: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BackgroundWorkerSettings? {
    let requiresCharging = pigeonVar_list[0] as! Bool
    let requiresBatteryNotLow = pigeonVar_list[1] as! Bool
    let minimumDelaySeconds = pigeonVar_list[2] as! Int64
    let requiresNetworkType = pigeonVar_list[3] as! Bool

    return BackgroundWorkerSettings(
      requiresCharging: requiresCharging,
      requiresBatteryNotLow: requiresBatteryNotLow,
      minimumDelaySeconds: minimumDelaySeconds,
      requiresNetworkType: requiresNetworkType
    )
  }
  func toList() -> [Any?] {
    return [
      requiresCharging,
      requiresBatteryNotLow,
      minimumDelaySeconds,
      requiresNetworkType,
    ]
  }
}

private class BackgroundWorkerPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return BackgroundWorkerSettings.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BackgroundWorkerPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BackgroundWorkerSettings {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BackgroundWorkerPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BackgroundWorkerPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BackgroundWorkerPigeonCodecWriter(data: data)
  }
}

class BackgroundWorkerPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BackgroundWorkerPigeonCodec(readerWriter: BackgroundWorkerPigeonCodecReaderWriter())
}

/// 前台 API（Foreground API）
/// 从 Flutter 前台应用调用原生平台的 API
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BackgroundWorkerFgHostApi {
  /// 启用后台任务
  /// [callbackHandle] - Flutter回调函数句柄
  /// [notificationTitle] - 通知标题
  /// [immediate] - 是否立即执行
  func enable(callbackHandle: Int64, notificationTitle: String, immediate: Bool) throws
  /// 禁用后台任务
  func disable() throws
  /// 配置任务参数
  func configure(settings: BackgroundWorkerSettings) throws
  /// 保存通知消息
  func saveNotificationMessage(title: String, body: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BackgroundWorkerFgHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BackgroundWorkerPigeonCodec.shared }
  /// Sets up an instance of `BackgroundWorkerFgHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BackgroundWorkerFgHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 启用后台任务
    /// [callbackHandle] - Flutter回调函数句柄
    /// [notificationTitle] - 通知标题
    /// [immediate] - 是否立即执行
    let enableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.BackgroundWorkerFgHostApi.enable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let callbackHandleArg = args[0] as! Int64
        let notificationTitleArg = args[1] as! String
        let immediateArg = args[2] as! Bool
        do {
          try api.enable(callbackHandle: callbackHandleArg, notificationTitle: notificationTitleArg, immediate: immediateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      enableChannel.setMessageHandler(nil)
    }
    /// 禁用后台任务
    let disableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.BackgroundWorkerFgHostApi.disable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disableChannel.setMessageHandler { _, reply in
        do {
          try api.disable()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disableChannel.setMessageHandler(nil)
    }
    /// 配置任务参数
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.BackgroundWorkerFgHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! BackgroundWorkerSettings
        do {
          try api.configure(settings: settingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    /// 保存通知消息
    let saveNotificationMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.BackgroundWorkerFgHostApi.saveNotificationMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveNotificationMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let titleArg = args[0] as! String
        let bodyArg = args[1] as! String
        do {
          try api.saveNotificationMessage(title: titleArg, body: bodyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveNotificationMessageChannel.setMessageHandler(nil)
    }
  }
}
/// 后台 API（Background API）
/// 从后台 Flutter Engine 调用原生平台的 API
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BackgroundWorkerBgHostApi {
  /// 通知原生层初始化完成
  /// 当后台 Flutter Engine 初始化完成并建立必要的平台通道后调用
  func onInitialized() throws
  /// 通知原生层任务完成
  /// 当后台任务执行完成后调用
  func onCompleted() throws
  /// 更新进度
  /// [uploadedCount] - 已上传数量
  /// [totalCount] - 总数量
  /// [currentFileName] - 当前文件名（可选）
  func updateProgress(uploadedCount: Int64, totalCount: Int64, currentFileName: String?) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BackgroundWorkerBgHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BackgroundWorkerPigeonCodec.shared }
  /// Sets up an instance of `BackgroundWorkerBgHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BackgroundWorkerBgHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 通知原生层初始化完成
    /// 当后台 Flutter Engine 初始化完成并建立必要的平台通道后调用
    let onInitializedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.BackgroundWorkerBgHostApi.onInitialized\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onInitializedChannel.setMessageHandler { _, reply in
        do {
          try api.onInitialized()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onInitializedChannel.setMessageHandler(nil)
    }
    /// 通知原生层任务完成
    /// 当后台任务执行完成后调用
    let onCompletedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.BackgroundWorkerBgHostApi.onCompleted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onCompletedChannel.setMessageHandler { _, reply in
        do {
          try api.onCompleted()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onCompletedChannel.setMessageHandler(nil)
    }
    /// 更新进度
    /// [uploadedCount] - 已上传数量
    /// [totalCount] - 总数量
    /// [currentFileName] - 当前文件名（可选）
    let updateProgressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.BackgroundWorkerBgHostApi.updateProgress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateProgressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uploadedCountArg = args[0] as! Int64
        let totalCountArg = args[1] as! Int64
        let currentFileNameArg: String? = nilOrValue(args[2])
        do {
          try api.updateProgress(uploadedCount: uploadedCountArg, totalCount: totalCountArg, currentFileName: currentFileNameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateProgressChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API
/// 从原生平台调用 Flutter 的 API
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BackgroundWorkerFlutterApiProtocol {
  /// iOS 专用：iOS 后台上传触发
  /// [isRefresh] - 是否为刷新任务（BGAppRefreshTask）
  /// [maxSeconds] - 最大执行时间（秒），BGProcessingTask 使用
  func onIosUpload(isRefresh isRefreshArg: Bool, maxSeconds maxSecondsArg: Int64?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Android 专用：Android 后台上传触发
  func onAndroidUpload(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// 取消任务
  func cancel(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BackgroundWorkerFlutterApi: BackgroundWorkerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: BackgroundWorkerPigeonCodec {
    return BackgroundWorkerPigeonCodec.shared
  }
  /// iOS 专用：iOS 后台上传触发
  /// [isRefresh] - 是否为刷新任务（BGAppRefreshTask）
  /// [maxSeconds] - 最大执行时间（秒），BGProcessingTask 使用
  func onIosUpload(isRefresh isRefreshArg: Bool, maxSeconds maxSecondsArg: Int64?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.prismbox.BackgroundWorkerFlutterApi.onIosUpload\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isRefreshArg, maxSecondsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Android 专用：Android 后台上传触发
  func onAndroidUpload(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.prismbox.BackgroundWorkerFlutterApi.onAndroidUpload\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// 取消任务
  func cancel(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.prismbox.BackgroundWorkerFlutterApi.cancel\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
