// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.prismbox.background

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * 后台任务配置设置
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BackgroundWorkerSettings (
  /** 是否要求充电 */
  val requiresCharging: Boolean,
  /** 是否要求电池不低 */
  val requiresBatteryNotLow: Boolean,
  /** 最小延迟秒数 */
  val minimumDelaySeconds: Long,
  /** 网络类型要求（true表示需要WiFi，false表示不限制） */
  val requiresNetworkType: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BackgroundWorkerSettings {
      val requiresCharging = pigeonVar_list[0] as Boolean
      val requiresBatteryNotLow = pigeonVar_list[1] as Boolean
      val minimumDelaySeconds = pigeonVar_list[2] as Long
      val requiresNetworkType = pigeonVar_list[3] as Boolean
      return BackgroundWorkerSettings(requiresCharging, requiresBatteryNotLow, minimumDelaySeconds, requiresNetworkType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requiresCharging,
      requiresBatteryNotLow,
      minimumDelaySeconds,
      requiresNetworkType,
    )
  }
}
private open class BackgroundWorkerPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BackgroundWorkerSettings.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BackgroundWorkerSettings -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * 前台 API（Foreground API）
 * 从 Flutter 前台应用调用原生平台的 API
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface BackgroundWorkerFgHostApi {
  /**
   * 启用后台任务
   * [callbackHandle] - Flutter回调函数句柄
   * [notificationTitle] - 通知标题
   * [immediate] - 是否立即执行
   */
  fun enable(callbackHandle: Long, notificationTitle: String, immediate: Boolean)
  /** 禁用后台任务 */
  fun disable()
  /** 配置任务参数 */
  fun configure(settings: BackgroundWorkerSettings)
  /** 保存通知消息 */
  fun saveNotificationMessage(title: String, body: String)

  companion object {
    /** The codec used by BackgroundWorkerFgHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      BackgroundWorkerPigeonCodec()
    }
    /** Sets up an instance of `BackgroundWorkerFgHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BackgroundWorkerFgHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.BackgroundWorkerFgHostApi.enable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val callbackHandleArg = args[0] as Long
            val notificationTitleArg = args[1] as String
            val immediateArg = args[2] as Boolean
            val wrapped: List<Any?> = try {
              api.enable(callbackHandleArg, notificationTitleArg, immediateArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.BackgroundWorkerFgHostApi.disable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disable()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.BackgroundWorkerFgHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as BackgroundWorkerSettings
            val wrapped: List<Any?> = try {
              api.configure(settingsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.BackgroundWorkerFgHostApi.saveNotificationMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String
            val bodyArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.saveNotificationMessage(titleArg, bodyArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * 后台 API（Background API）
 * 从后台 Flutter Engine 调用原生平台的 API
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface BackgroundWorkerBgHostApi {
  /**
   * 通知原生层初始化完成
   * 当后台 Flutter Engine 初始化完成并建立必要的平台通道后调用
   */
  fun onInitialized()
  /**
   * 通知原生层任务完成
   * 当后台任务执行完成后调用
   */
  fun onCompleted()
  /**
   * 更新进度
   * [uploadedCount] - 已上传数量
   * [totalCount] - 总数量
   * [currentFileName] - 当前文件名（可选）
   */
  fun updateProgress(uploadedCount: Long, totalCount: Long, currentFileName: String?)
  /**
   * 检查内容是否已变化（Android 专用）
   * 返回 true 表示在备份执行期间有新内容变化
   */
  fun hasContentChanged(): Boolean

  companion object {
    /** The codec used by BackgroundWorkerBgHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      BackgroundWorkerPigeonCodec()
    }
    /** Sets up an instance of `BackgroundWorkerBgHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BackgroundWorkerBgHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.BackgroundWorkerBgHostApi.onInitialized$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.onInitialized()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.BackgroundWorkerBgHostApi.onCompleted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.onCompleted()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.BackgroundWorkerBgHostApi.updateProgress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uploadedCountArg = args[0] as Long
            val totalCountArg = args[1] as Long
            val currentFileNameArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.updateProgress(uploadedCountArg, totalCountArg, currentFileNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.BackgroundWorkerBgHostApi.hasContentChanged$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasContentChanged())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API
 * 从原生平台调用 Flutter 的 API
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class BackgroundWorkerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by BackgroundWorkerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      BackgroundWorkerPigeonCodec()
    }
  }
  /**
   * iOS 专用：iOS 后台上传触发
   * [isRefresh] - 是否为刷新任务（BGAppRefreshTask）
   * [maxSeconds] - 最大执行时间（秒），BGProcessingTask 使用
   */
  fun onIosUpload(isRefreshArg: Boolean, maxSecondsArg: Long?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.prismbox.BackgroundWorkerFlutterApi.onIosUpload$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(isRefreshArg, maxSecondsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Android 专用：Android 后台上传触发 */
  fun onAndroidUpload(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.prismbox.BackgroundWorkerFlutterApi.onAndroidUpload$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** 取消任务 */
  fun cancel(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.prismbox.BackgroundWorkerFlutterApi.cancel$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
