// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/albums": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的所有相册列表。为提高性能，此接口不包含媒体内容，只包含数量统计。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Albums"
                ],
                "summary": "获取相册列表",
                "responses": {
                    "200": {
                        "description": "成功获取相册列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Album"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "数据库错误",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为当前登录的用户创建一个新的相册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Albums"
                ],
                "summary": "创建新相册",
                "parameters": [
                    {
                        "description": "相册信息",
                        "name": "album",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateAlbumInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "相册创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Album"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误或服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/albums/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取单个相册及其包含的所有媒体项（分页）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Albums"
                ],
                "summary": "获取单个相册详情",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "相册的UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取相册详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Album"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "错误信息可能为 'Album not found or permission denied'",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除相册（软删除）。注意：这只删除相册和关联记录，不删除原始的照片文件。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Albums"
                ],
                "summary": "删除相册",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "相册的UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "相册删除成功",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "错误信息可能为 'Album not found' 或 'Failed to delete'",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/albums/{uuid}/items": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "向指定相册添加一个或多个媒体项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Albums"
                ],
                "summary": "向相册添加媒体",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "目标相册的UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "要添加的媒体UUID列表",
                        "name": "photo_uuids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AddItemsToAlbumInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "媒体项添加成功",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误、相册或照片未找到、无权限等",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "使用用户名和密码进行登录，成功后返回访问令牌和刷新令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录凭证",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserLoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.UserLoginSuccessData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误、用户名或密码无效或服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "通过撤销指定的刷新令牌来实现服务端登出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "description": "刷新令牌",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LogoutInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功登出",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或令牌无效",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "使用一个有效的、未过期的刷新令牌来获取一个新的访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "刷新访问令牌",
                "parameters": [
                    {
                        "description": "刷新令牌",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokenInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功刷新令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.RefreshTokenSuccessData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误或刷新令牌无效、已过期或已被撤销",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "根据用户名、邮箱和密码创建一个新的用户账户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "注册新用户",
                "parameters": [
                    {
                        "description": "用户注册信息",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserRegisterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户注册成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.UserRegisterSuccessData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误、用户已存在或服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/photos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的所有媒体列表（分页）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Photos"
                ],
                "summary": "获取媒体列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取媒体列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Photo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "数据库错误",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/photos/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "通过 multipart/form-data 上传照片或视频。服务器会先进行秒传检查。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Photos"
                ],
                "summary": "上传单个媒体文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "媒体文件本身",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件的SHA256哈希值",
                        "name": "hash",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "IMAGE",
                            "VIDEO"
                        ],
                        "type": "string",
                        "description": "媒体类型 (IMAGE 或 VIDEO)",
                        "name": "item_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件的原始名称",
                        "name": "original_filename",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件已存在（秒传成功）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Photo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "201": {
                        "description": "上传成功，后台处理开始",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Photo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误、文件上传失败或服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/photos/{uuid}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将指定的媒体文件移入回收站（软删除）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Photos"
                ],
                "summary": "删除指定的媒体文件",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "媒体文件的UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功删除",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "错误信息可能为 'Photo not found or permission denied' 或 'Database error'",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/photos/{uuid}/download/original": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "下载指定UUID的原始媒体文件。",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Photos"
                ],
                "summary": "下载原始文件",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "媒体文件的UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "原始文件数据",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "错误信息可能为 'Photo not found' 或 'File is not ready yet'",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/photos/{uuid}/download/preview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定UUID的预览文件 (图片为 .jpg, 视频为 .mp4)。",
                "produces": [
                    "image/jpeg",
                    "video/mp4"
                ],
                "tags": [
                    "Photos"
                ],
                "summary": "获取预览图或预览视频",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "媒体文件的UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "预览文件数据",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "错误信息可能为 'Preview not found' 或 'Preview is not ready yet'",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/photos/{uuid}/download/thumbnail": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定UUID的缩略图 (统一为 .jpg 格式)。",
                "produces": [
                    "image/jpeg"
                ],
                "tags": [
                    "Photos"
                ],
                "summary": "获取缩略图",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "媒体文件的UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "缩略图文件数据",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "错误信息可能为 'Thumbnail not found' 或 'Thumbnail is not ready yet'",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/s/{share_token}": {
            "get": {
                "description": "通过一个公开的分享令牌访问媒体资源。服务器会返回一个包含临时签名URL的HTML页面。",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "访问分享的资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享令牌",
                        "name": "share_token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "包含媒体资源的HTML页面",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "分享链接不存在",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    },
                    "410": {
                        "description": "分享链接已过期或被撤销",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/shares": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为指定的媒体资源创建一个分享。可以分享给特定用户（通过ID）或游客。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shares"
                ],
                "summary": "创建分享链接",
                "parameters": [
                    {
                        "description": "分享信息",
                        "name": "share_info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateShareInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "成功创建，返回公开分享链接",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "照片或目标用户未找到",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        },
        "/shares/with-me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "列出其他用户分享给当前登录用户的所有有效媒体",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shares"
                ],
                "summary": "查看分享给我的内容",
                "responses": {
                    "200": {
                        "description": "成功获取列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Share"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/shares/{share_token}/meta": {
            "get": {
                "description": "通过分享令牌获取媒体资源的元数据和临时的下载URL。这是为移动端等API客户端设计的。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shares"
                ],
                "summary": "获取分享元数据 (API客户端使用)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享令牌",
                        "name": "share_token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功，返回照片元数据，并在其中动态添加一个临时的signed_url字段",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Photo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "分享链接不存在",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    },
                    "410": {
                        "description": "分享链接已过期或被撤销",
                        "schema": {
                            "$ref": "#/definitions/core.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LogoutInput": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "auth.RefreshTokenInput": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "auth.RefreshTokenSuccessData": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "auth.UserLoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "aVeryStrongPassword123"
                },
                "username": {
                    "type": "string",
                    "example": "newuser"
                }
            }
        },
        "auth.UserLoginSuccessData": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "auth.UserRegisterInput": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "aVeryStrongPassword123"
                },
                "username": {
                    "type": "string",
                    "example": "newuser"
                }
            }
        },
        "auth.UserRegisterSuccessData": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "newuser"
                }
            }
        },
        "constant.MediaType": {
            "type": "string",
            "enum": [
                "IMAGE",
                "VIDEO"
            ],
            "x-enum-varnames": [
                "TypeImage",
                "TypeVideo"
            ]
        },
        "constant.ProcessingStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "COMPLETED",
                "FAILED"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusCompleted",
                "StatusFailed"
            ]
        },
        "core.ApiResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.AddItemsToAlbumInput": {
            "type": "object",
            "required": [
                "photo_uuids"
            ],
            "properties": {
                "photo_uuids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"d8a2a7f0-4b3e-4b6e-9e7b-8d7c2a7f04b3\"]"
                    ]
                }
            }
        },
        "handlers.CreateAlbumInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "2025年春节的欢乐时光"
                },
                "name": {
                    "type": "string",
                    "example": "我的家庭聚会"
                }
            }
        },
        "handlers.CreateShareInput": {
            "type": "object",
            "required": [
                "duration_minute",
                "photo_uuid"
            ],
            "properties": {
                "duration_minute": {
                    "type": "integer",
                    "minimum": 1
                },
                "photo_uuid": {
                    "type": "string"
                },
                "target_user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Album": {
            "type": "object",
            "properties": {
                "cover_photo_uuid": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "item_count": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Photo"
                    }
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "description": "❗ 核心改动: 关联用户",
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "models.Photo": {
            "type": "object",
            "properties": {
                "aperture": {
                    "type": "string"
                },
                "camera_make": {
                    "type": "string"
                },
                "camera_model": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "file_size": {
                    "type": "integer"
                },
                "filename": {
                    "type": "string"
                },
                "hash": {
                    "description": "联合唯一索引",
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "iso": {
                    "type": "integer"
                },
                "item_type": {
                    "$ref": "#/definitions/constant.MediaType"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "mime_type": {
                    "type": "string"
                },
                "original_filename": {
                    "type": "string"
                },
                "photo_taken_at": {
                    "type": "string"
                },
                "processing_status": {
                    "$ref": "#/definitions/constant.ProcessingStatus"
                },
                "shutter_speed": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "description": "❗ 核心改动: 关联用户",
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "models.Share": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "expiresAt": {
                    "description": "分享的过期时间",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isRevoked": {
                    "description": "是否已被创建者手动撤销",
                    "type": "boolean"
                },
                "owner": {
                    "$ref": "#/definitions/models.User"
                },
                "ownerID": {
                    "description": "分享的创建者",
                    "type": "integer"
                },
                "photo": {
                    "$ref": "#/definitions/models.Photo"
                },
                "photoID": {
                    "description": "分享的是哪个照片",
                    "type": "integer"
                },
                "shareToken": {
                    "description": "用于公开分享链接的唯一令牌",
                    "type": "string"
                },
                "targetUser": {
                    "$ref": "#/definitions/models.User"
                },
                "targetUserID": {
                    "description": "分享给谁 (如果为NULL，则为游客分享)",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and a JWT.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "用户注册与登录",
            "name": "Authentication"
        },
        {
            "description": "照片和视频的上传、查询和管理",
            "name": "Photos"
        },
        {
            "description": "相册管理",
            "name": "Albums"
        },
        {
            "description": "共享资源",
            "name": "Shares"
        },
        {
            "description": "获取共享资源",
            "name": "Public"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "媒体管理 API",
	Description:      "一个用于上传、管理和浏览照片与视频的后端服务 API。\n该 API 支持用户认证、多媒体处理、相册管理，并提供标准化的响应格式。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
