// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.prismbox.images

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
private open class ThumbnailsPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/**
 * 缩略图解码 API
 * 从 Flutter 调用原生平台的图片解码功能，支持 RAW 格式和视频缩略图
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ThumbnailApi {
  /**
   * 请求图片解码
   *
   * **参数**：
   * - [assetId] - 资源 ID（本地资源标识符）
   * - [requestId] - 请求 ID（用于取消请求）
   * - [width] - 目标宽度（像素）
   * - [height] - 目标高度（像素）
   * - [isVideo] - 是否为视频资源
   *
   * **返回值**：
   * - `Map<String, int>` 包含：
   *   - `pointer`: 原生内存指针地址
   *   - `width`: 实际图片宽度
   *   - `height`: 实际图片高度
   *   - 空 Map 表示请求已取消
   */
  fun requestImage(assetId: String, requestId: Long, width: Long, height: Long, isVideo: Boolean, callback: (Result<Map<String, Long>>) -> Unit)
  /**
   * 取消图片请求
   *
   * **参数**：
   * - [requestId] - 要取消的请求 ID
   */
  fun cancelImageRequest(requestId: Long)
  /**
   * 解码 ThumbHash 为 RGBA 图片
   *
   * **参数**：
   * - [thumbhash] - Base64 编码的 ThumbHash 字符串
   *
   * **返回值**：
   * - `Map<String, int>` 包含：
   *   - `pointer`: 原生内存指针地址
   *   - `width`: 图片宽度
   *   - `height`: 图片高度
   */
  fun getThumbhash(thumbhash: String, callback: (Result<Map<String, Long>>) -> Unit)

  companion object {
    /** The codec used by ThumbnailApi. */
    val codec: MessageCodec<Any?> by lazy {
      ThumbnailsPigeonCodec()
    }
    /** Sets up an instance of `ThumbnailApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ThumbnailApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.ThumbnailApi.requestImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val assetIdArg = args[0] as String
            val requestIdArg = args[1] as Long
            val widthArg = args[2] as Long
            val heightArg = args[3] as Long
            val isVideoArg = args[4] as Boolean
            api.requestImage(assetIdArg, requestIdArg, widthArg, heightArg, isVideoArg) { result: Result<Map<String, Long>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.ThumbnailApi.cancelImageRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelImageRequest(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.ThumbnailApi.getThumbhash$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val thumbhashArg = args[0] as String
            api.getThumbhash(thumbhashArg) { result: Result<Map<String, Long>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
