// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// Note: PigeonError and helper functions are defined as internal in Thumbnails.g.swift

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

// PigeonError, wrapResult, wrapError, isNullish, and nilOrValue are defined in Thumbnails.g.swift as internal

/// 资产元数据
/// 包含资产 ID 和收藏状态等信息
///
/// Generated class from Pigeon that represents data sent in messages.
struct AssetMetadata {
  /// 资产 ID（本地资源标识符）
  var id: String
  /// 是否收藏
  var isFavorite: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AssetMetadata? {
    let id = pigeonVar_list[0] as! String
    let isFavorite = pigeonVar_list[1] as! Bool

    return AssetMetadata(
      id: id,
      isFavorite: isFavorite
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      isFavorite,
    ]
  }
}

private class AssetNativePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AssetMetadata.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AssetNativePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AssetMetadata {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AssetNativePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AssetNativePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AssetNativePigeonCodecWriter(data: data)
  }
}

class AssetNativePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AssetNativePigeonCodec(readerWriter: AssetNativePigeonCodecReaderWriter())
}


/// 资产原生 API
/// 从 Flutter 调用原生平台获取系统相册资产的元数据
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AssetNativeApi {
  /// 获取单个资产的收藏状态
  ///
  /// **参数**：
  /// - [assetId] - 资产 ID（本地资源标识符）
  ///
  /// **返回值**：
  /// - `bool` 表示资产是否被收藏
  /// - 如果资产不存在或获取失败，返回 `false`
  ///
  /// **平台说明**：
  /// - iOS：通过 PHAsset.isFavorite 属性获取
  /// - Android：通过 MediaStore.MediaColumns.IS_FAVORITE 字段查询（仅 Android 11+）
  /// - Android 10 及以下版本始终返回 false
  func getIsFavorite(assetId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// 批量获取资产元数据
  ///
  /// **参数**：
  /// - [assetIds] - 资产 ID 列表
  ///
  /// **返回值**：
  /// - `List<AssetMetadata>` 包含每个资产的元数据
  /// - 如果某个资产不存在，该资产不会出现在结果中
  ///
  /// **性能说明**：
  /// - 批量获取比逐个调用 getIsFavorite 更高效
  /// - 建议每批不超过 100 个资产
  func getAssetMetadata(assetIds: [String], completion: @escaping (Result<[AssetMetadata], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AssetNativeApiSetup {
  static var codec: FlutterStandardMessageCodec { AssetNativePigeonCodec.shared }
  /// Sets up an instance of `AssetNativeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AssetNativeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 获取单个资产的收藏状态
    ///
    /// **参数**：
    /// - [assetId] - 资产 ID（本地资源标识符）
    ///
    /// **返回值**：
    /// - `bool` 表示资产是否被收藏
    /// - 如果资产不存在或获取失败，返回 `false`
    ///
    /// **平台说明**：
    /// - iOS：通过 PHAsset.isFavorite 属性获取
    /// - Android：通过 MediaStore.MediaColumns.IS_FAVORITE 字段查询（仅 Android 11+）
    /// - Android 10 及以下版本始终返回 false
    let getIsFavoriteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.AssetNativeApi.getIsFavorite\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIsFavoriteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetIdArg = args[0] as! String
        api.getIsFavorite(assetId: assetIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getIsFavoriteChannel.setMessageHandler(nil)
    }
    /// 批量获取资产元数据
    ///
    /// **参数**：
    /// - [assetIds] - 资产 ID 列表
    ///
    /// **返回值**：
    /// - `List<AssetMetadata>` 包含每个资产的元数据
    /// - 如果某个资产不存在，该资产不会出现在结果中
    ///
    /// **性能说明**：
    /// - 批量获取比逐个调用 getIsFavorite 更高效
    /// - 建议每批不超过 100 个资产
    let getAssetMetadataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.AssetNativeApi.getAssetMetadata\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAssetMetadataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetIdsArg = args[0] as! [String]
        api.getAssetMetadata(assetIds: assetIdsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAssetMetadataChannel.setMessageHandler(nil)
    }
  }
}
