// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.prismbox.connectivity

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** 网络能力枚举 */
enum class NetworkCapability(val raw: Int) {
  /** WiFi 连接 */
  WIFI(0),
  /** 移动数据连接 */
  CELLULAR(1),
  /** VPN 连接 */
  VPN(2),
  /** 无流量限制的网络（通常是 WiFi） */
  UNMETERED(3);

  companion object {
    fun ofRaw(raw: Int): NetworkCapability? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * 网络连接信息
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NetworkInfo (
  /** 是否有网络连接 */
  val isConnected: Boolean,
  /** 网络能力列表 */
  val capabilities: List<NetworkCapability>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NetworkInfo {
      val isConnected = pigeonVar_list[0] as Boolean
      val capabilities = pigeonVar_list[1] as List<NetworkCapability>
      return NetworkInfo(isConnected, capabilities)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isConnected,
      capabilities,
    )
  }
}
private open class ConnectivityPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NetworkCapability.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NetworkInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NetworkCapability -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is NetworkInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * 网络连接检查 API
 * 从 Flutter 调用原生平台的网络检查功能
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ConnectivityApi {
  /** 获取当前网络连接信息 */
  fun getNetworkInfo(): NetworkInfo
  /**
   * 检查是否连接 WiFi
   * 
   * **返回值**：
   * - `true`：已连接 WiFi
   * - `false`：未连接 WiFi 或无法确定
   */
  fun isWifiConnected(): Boolean
  /**
   * 检查是否有网络连接
   * 
   * **返回值**：
   * - `true`：有网络连接
   * - `false`：无网络连接
   */
  fun hasNetworkConnection(): Boolean

  companion object {
    /** The codec used by ConnectivityApi. */
    val codec: MessageCodec<Any?> by lazy {
      ConnectivityPigeonCodec()
    }
    /** Sets up an instance of `ConnectivityApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ConnectivityApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.ConnectivityApi.getNetworkInfo$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNetworkInfo())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.ConnectivityApi.isWifiConnected$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isWifiConnected())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.ConnectivityApi.hasNetworkConnection$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasNetworkConnection())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
