// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class ThumbnailsPigeonCodecReader: FlutterStandardReader {
}

private class ThumbnailsPigeonCodecWriter: FlutterStandardWriter {
}

private class ThumbnailsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ThumbnailsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ThumbnailsPigeonCodecWriter(data: data)
  }
}

class ThumbnailsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ThumbnailsPigeonCodec(readerWriter: ThumbnailsPigeonCodecReaderWriter())
}


/// 缩略图解码 API
/// 从 Flutter 调用原生平台的图片解码功能，支持 RAW 格式和视频缩略图
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ThumbnailApi {
  /// 请求图片解码
  ///
  /// **参数**：
  /// - [assetId] - 资源 ID（本地资源标识符）
  /// - [requestId] - 请求 ID（用于取消请求）
  /// - [width] - 目标宽度（像素）
  /// - [height] - 目标高度（像素）
  /// - [isVideo] - 是否为视频资源
  ///
  /// **返回值**：
  /// - `Map<String, int>` 包含：
  ///   - `pointer`: 原生内存指针地址
  ///   - `width`: 实际图片宽度
  ///   - `height`: 实际图片高度
  ///   - 空 Map 表示请求已取消
  func requestImage(assetId: String, requestId: Int64, width: Int64, height: Int64, isVideo: Bool, completion: @escaping (Result<[String: Int64], Error>) -> Void)
  /// 取消图片请求
  ///
  /// **参数**：
  /// - [requestId] - 要取消的请求 ID
  func cancelImageRequest(requestId: Int64) throws
  /// 解码 ThumbHash 为 RGBA 图片
  ///
  /// **参数**：
  /// - [thumbhash] - Base64 编码的 ThumbHash 字符串
  ///
  /// **返回值**：
  /// - `Map<String, int>` 包含：
  ///   - `pointer`: 原生内存指针地址
  ///   - `width`: 图片宽度
  ///   - `height`: 图片高度
  func getThumbhash(thumbhash: String, completion: @escaping (Result<[String: Int64], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ThumbnailApiSetup {
  static var codec: FlutterStandardMessageCodec { ThumbnailsPigeonCodec.shared }
  /// Sets up an instance of `ThumbnailApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ThumbnailApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 请求图片解码
    ///
    /// **参数**：
    /// - [assetId] - 资源 ID（本地资源标识符）
    /// - [requestId] - 请求 ID（用于取消请求）
    /// - [width] - 目标宽度（像素）
    /// - [height] - 目标高度（像素）
    /// - [isVideo] - 是否为视频资源
    ///
    /// **返回值**：
    /// - `Map<String, int>` 包含：
    ///   - `pointer`: 原生内存指针地址
    ///   - `width`: 实际图片宽度
    ///   - `height`: 实际图片高度
    ///   - 空 Map 表示请求已取消
    let requestImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.ThumbnailApi.requestImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetIdArg = args[0] as! String
        let requestIdArg = args[1] as! Int64
        let widthArg = args[2] as! Int64
        let heightArg = args[3] as! Int64
        let isVideoArg = args[4] as! Bool
        api.requestImage(assetId: assetIdArg, requestId: requestIdArg, width: widthArg, height: heightArg, isVideo: isVideoArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestImageChannel.setMessageHandler(nil)
    }
    /// 取消图片请求
    ///
    /// **参数**：
    /// - [requestId] - 要取消的请求 ID
    let cancelImageRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.ThumbnailApi.cancelImageRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelImageRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        do {
          try api.cancelImageRequest(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelImageRequestChannel.setMessageHandler(nil)
    }
    /// 解码 ThumbHash 为 RGBA 图片
    ///
    /// **参数**：
    /// - [thumbhash] - Base64 编码的 ThumbHash 字符串
    ///
    /// **返回值**：
    /// - `Map<String, int>` 包含：
    ///   - `pointer`: 原生内存指针地址
    ///   - `width`: 图片宽度
    ///   - `height`: 图片高度
    let getThumbhashChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.ThumbnailApi.getThumbhash\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getThumbhashChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let thumbhashArg = args[0] as! String
        api.getThumbhash(thumbhash: thumbhashArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getThumbhashChannel.setMessageHandler(nil)
    }
  }
}
