// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// 资产元数据
/// 包含资产 ID 和收藏状态等信息
class AssetMetadata {
  AssetMetadata({
    required this.id,
    required this.isFavorite,
  });

  /// 资产 ID（本地资源标识符）
  String id;

  /// 是否收藏
  bool isFavorite;

  Object encode() {
    return <Object?>[
      id,
      isFavorite,
    ];
  }

  static AssetMetadata decode(Object result) {
    result as List<Object?>;
    return AssetMetadata(
      id: result[0]! as String,
      isFavorite: result[1]! as bool,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AssetMetadata) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return AssetMetadata.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// 资产原生 API
/// 从 Flutter 调用原生平台获取系统相册资产的元数据
class AssetNativeApi {
  /// Constructor for [AssetNativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AssetNativeApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 获取单个资产的收藏状态
  ///
  /// **参数**：
  /// - [assetId] - 资产 ID（本地资源标识符）
  ///
  /// **返回值**：
  /// - `bool` 表示资产是否被收藏
  /// - 如果资产不存在或获取失败，返回 `false`
  ///
  /// **平台说明**：
  /// - iOS：通过 PHAsset.isFavorite 属性获取
  /// - Android：通过 MediaStore.MediaColumns.IS_FAVORITE 字段查询（仅 Android 11+）
  /// - Android 10 及以下版本始终返回 false
  Future<bool> getIsFavorite(String assetId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.prismbox.AssetNativeApi.getIsFavorite$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[assetId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// 批量获取资产元数据
  ///
  /// **参数**：
  /// - [assetIds] - 资产 ID 列表
  ///
  /// **返回值**：
  /// - `List<AssetMetadata>` 包含每个资产的元数据
  /// - 如果某个资产不存在，该资产不会出现在结果中
  ///
  /// **性能说明**：
  /// - 批量获取比逐个调用 getIsFavorite 更高效
  /// - 建议每批不超过 100 个资产
  Future<List<AssetMetadata>> getAssetMetadata(List<String> assetIds) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.prismbox.AssetNativeApi.getAssetMetadata$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[assetIds]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<AssetMetadata>();
    }
  }

  /// 设置系统相册中资产的收藏状态（写回系统，与 DB 一致以便下次同步不被覆盖）
  ///
  /// **参数**：
  /// - [assetId] - 资产 ID（iOS 为 localIdentifier，Android 为 MediaStore _ID）
  /// - [isFavorite] - 是否收藏
  ///
  /// **权限**：
  /// - iOS：需要相册「读写」权限（PHAuthorizationStatus 且 requestAccess 为 readWrite）
  /// - Android：需要存储/相册写入权限（Android 11+ 使用 MediaStore 更新 IS_FAVORITE）
  ///
  /// **失败**：无权限或资产不存在时通过异常返回，调用方应捕获并降级（仅保留 DB 更新）。
  Future<void> setIsFavorite(String assetId, bool isFavorite) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.prismbox.AssetNativeApi.setIsFavorite$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[assetId, isFavorite]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
