name: flutter_replicator
description: A client-side replication package designed to sync local data with a changelog-based backend service. It is highly decoupled and easy to integrate.
version: 1.0.0
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
