// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.prismbox.assets

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 资产元数据
 * 包含资产 ID 和收藏状态等信息
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AssetMetadata (
  /** 资产 ID（本地资源标识符） */
  val id: String,
  /** 是否收藏 */
  val isFavorite: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AssetMetadata {
      val id = pigeonVar_list[0] as String
      val isFavorite = pigeonVar_list[1] as Boolean
      return AssetMetadata(id, isFavorite)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      isFavorite,
    )
  }
}
private open class AssetNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AssetMetadata.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AssetMetadata -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * 资产原生 API
 * 从 Flutter 调用原生平台获取系统相册资产的元数据
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AssetNativeApi {
  /**
   * 获取单个资产的收藏状态
   *
   * **参数**：
   * - [assetId] - 资产 ID（本地资源标识符）
   *
   * **返回值**：
   * - `bool` 表示资产是否被收藏
   * - 如果资产不存在或获取失败，返回 `false`
   *
   * **平台说明**：
   * - iOS：通过 PHAsset.isFavorite 属性获取
   * - Android：通过 MediaStore.MediaColumns.IS_FAVORITE 字段查询（仅 Android 11+）
   * - Android 10 及以下版本始终返回 false
   */
  fun getIsFavorite(assetId: String, callback: (Result<Boolean>) -> Unit)
  /**
   * 批量获取资产元数据
   *
   * **参数**：
   * - [assetIds] - 资产 ID 列表
   *
   * **返回值**：
   * - `List<AssetMetadata>` 包含每个资产的元数据
   * - 如果某个资产不存在，该资产不会出现在结果中
   *
   * **性能说明**：
   * - 批量获取比逐个调用 getIsFavorite 更高效
   * - 建议每批不超过 100 个资产
   */
  fun getAssetMetadata(assetIds: List<String>, callback: (Result<List<AssetMetadata>>) -> Unit)
  /**
   * 设置系统相册中资产的收藏状态（写回系统，与 DB 一致以便下次同步不被覆盖）
   *
   * **参数**：
   * - [assetId] - 资产 ID（iOS 为 localIdentifier，Android 为 MediaStore _ID）
   * - [isFavorite] - 是否收藏
   *
   * **权限**：
   * - iOS：需要相册「读写」权限（PHAuthorizationStatus 且 requestAccess 为 readWrite）
   * - Android：需要存储/相册写入权限（Android 11+ 使用 MediaStore 更新 IS_FAVORITE）
   *
   * **失败**：无权限或资产不存在时通过异常返回，调用方应捕获并降级（仅保留 DB 更新）。
   */
  fun setIsFavorite(assetId: String, isFavorite: Boolean, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by AssetNativeApi. */
    val codec: MessageCodec<Any?> by lazy {
      AssetNativePigeonCodec()
    }
    /** Sets up an instance of `AssetNativeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AssetNativeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.AssetNativeApi.getIsFavorite$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val assetIdArg = args[0] as String
            api.getIsFavorite(assetIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.AssetNativeApi.getAssetMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val assetIdsArg = args[0] as List<String>
            api.getAssetMetadata(assetIdsArg) { result: Result<List<AssetMetadata>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prismbox.AssetNativeApi.setIsFavorite$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val assetIdArg = args[0] as String
            val isFavoriteArg = args[1] as Boolean
            api.setIsFavorite(assetIdArg, isFavoriteArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
