// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 网络能力枚举
enum NetworkCapability: Int {
  /// WiFi 连接
  case wifi = 0
  /// 移动数据连接
  case cellular = 1
  /// VPN 连接
  case vpn = 2
  /// 无流量限制的网络（通常是 WiFi）
  case unmetered = 3
}

/// 网络连接信息
///
/// Generated class from Pigeon that represents data sent in messages.
struct NetworkInfo {
  /// 是否有网络连接
  var isConnected: Bool
  /// 网络能力列表
  var capabilities: [NetworkCapability]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NetworkInfo? {
    let isConnected = pigeonVar_list[0] as! Bool
    let capabilities = pigeonVar_list[1] as! [NetworkCapability]

    return NetworkInfo(
      isConnected: isConnected,
      capabilities: capabilities
    )
  }
  func toList() -> [Any?] {
    return [
      isConnected,
      capabilities,
    ]
  }
}

private class ConnectivityPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NetworkCapability(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return NetworkInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ConnectivityPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NetworkCapability {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NetworkInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ConnectivityPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ConnectivityPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ConnectivityPigeonCodecWriter(data: data)
  }
}

class ConnectivityPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ConnectivityPigeonCodec(readerWriter: ConnectivityPigeonCodecReaderWriter())
}

/// 网络连接检查 API
/// 从 Flutter 调用原生平台的网络检查功能
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ConnectivityApi {
  /// 获取当前网络连接信息
  func getNetworkInfo() throws -> NetworkInfo
  /// 检查是否连接 WiFi
  /// 
  /// **返回值**：
  /// - `true`：已连接 WiFi
  /// - `false`：未连接 WiFi 或无法确定
  func isWifiConnected() throws -> Bool
  /// 检查是否有网络连接
  /// 
  /// **返回值**：
  /// - `true`：有网络连接
  /// - `false`：无网络连接
  func hasNetworkConnection() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ConnectivityApiSetup {
  static var codec: FlutterStandardMessageCodec { ConnectivityPigeonCodec.shared }
  /// Sets up an instance of `ConnectivityApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ConnectivityApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 获取当前网络连接信息
    let getNetworkInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.ConnectivityApi.getNetworkInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNetworkInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getNetworkInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNetworkInfoChannel.setMessageHandler(nil)
    }
    /// 检查是否连接 WiFi
    /// 
    /// **返回值**：
    /// - `true`：已连接 WiFi
    /// - `false`：未连接 WiFi 或无法确定
    let isWifiConnectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.ConnectivityApi.isWifiConnected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isWifiConnectedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isWifiConnected()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isWifiConnectedChannel.setMessageHandler(nil)
    }
    /// 检查是否有网络连接
    /// 
    /// **返回值**：
    /// - `true`：有网络连接
    /// - `false`：无网络连接
    let hasNetworkConnectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prismbox.ConnectivityApi.hasNetworkConnection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasNetworkConnectionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.hasNetworkConnection()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasNetworkConnectionChannel.setMessageHandler(nil)
    }
  }
}
